### PR TITLE
Improve TS type signature

### PR DESCRIPTION
**Pull request by stereobooster**
It is backward compatible, but as well you can specify type of items if you like

### CODE REVIEW

**Review by lukeed — COMMENTED** [review]
Hey, I'm not an avid TS user so can you explain the benefit of this to me? I believe `any` already includes `undefined` implicitly. It's so that you can set the Type of what you'll return?

**Comment by stereobooster** [comment]
Main change is that we allow to customise type of elements inside the cash. So we can do smoething like this

```ts
 private readonly cache: flruCache<FragmentFrame<Name>>;
 constructor(schema: Schema<Name>, data: Matrix<any>, prop: PivotProps<Name, Name>) {
    this.cache = flru(1024);
  }
```

and later when we will retrieve element (`this.cache.get(key)`) it will be `FragmentFrame<Name> | undefined` and not `any`

**Comment by stereobooster** [comment]
Actually I forgot to do this, but I would as well change `flruCache` to `FlruCache` types are traditionally capitalised. But this is optional (and breaking change).

**Comment by lukeed** [comment]
Cool, got it & thanks for explanation 👍 

I understand about the type naming convention, but the module name is lowercase so it felt a little more appropriate 😆 Perhaps not standard, but it works

**Pull request merged**
